config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  
  get '/posts/most_liked'

  devise_for :users
  resources :posts do 
    member do
      get "like", to: "posts#upvote"
    end
    resources :comments, only: [:create, :destroy]
  end
  resources :users
  
  scope "(:locale)", :locale => /en|ar/ do
  resources :posts
  root :to => "posts#index"
  end
  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :title, presence: true
    validates :image, presence: true 
    validates :link, presence: true
    validates :description, presence: true
    acts_as_votable
    belongs_to :user 
    has_many :comments
    has_attached_file :image, styles: { medium: "500x400>", small: "350x250>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :liked_posts, :through => :likes, :source => :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :set_locale
    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	  devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    
    def create
        @post = Post.find(params[:post_id])
        @comment = Comment.create(params[:comment].permit(:content))
        @comment.user_id = current_user.id
        @comment.post_id = @post.id
        
        
        respond_to do |format|
          if @comment.save
            format.html { redirect_to post_path(@post) }
            format.json { render :show, status: :created, location: @post }
          else
            flash[:danger] = 'يجب ملء حقل التعليق'
            format.html { redirect_to post_path(@post) }
            format.json { render json: @comment.errors, status: :unprocessable_entity }
          end
        end
    end
    
    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote]
    before_action :authenticate_user!, except: [:index, :show, :most_liked]
    
    def index
        @posts = Post.all.order("created_at DESC")
    end
    
    def most_liked
        @most_liked = Post.all.order(cached_votes_score: :DESC)
    end
    
    def show
        @comments = Comment.where(post_id: @post)
        @random_post = Post.where.not(id: @post).order("RANDOM()").first
    end
    
    def new
        @post = current_user.posts.build
    end
    
    def create
        @post = current_user.posts.build(post_params)
        
        
        respond_to do |format|
            if @post.save
              flash[:success] = 'تمت إضافة المشروع بنجاح.'
              format.html { redirect_to @post }
              format.json { render :show, status: :created, location: @post }
            else
              flash[:danger] = 'هناك مشكلة عند إضافة المشروع.'
              format.html { render :new }
              format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def edit
    end
    
    def update
        respond_to do |format|
            if @post.update(post_params)
              flash[:success] = 'تم تحديث المشروع بنجاح.'
              format.html { redirect_to @post }
              format.json { render :show, status: :ok, location: @post }
            else
              flash[:danger] = 'هناك مشكلة استكمال المشروع.'
              format.html { render :edit }
              format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def destroy
        @post.destroy
        redirect_to root_path
    end
    
    def upvote
        @post.upvote_by current_user
        redirect_to :back
    end

    private
    
    def find_post
        @post = Post.find(params[:id])
    end
    
    def post_params
        params.require(:post).permit(:title, :link, :description, :image)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  def show
    @user = current_user
    @user_posts = @user.posts
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
.comment
    %p= comment.comment
    %p= comment.user.name
    = button_to 'Delete', [comment.post, comment],
               :method => :delete,
               data: { confirm: 'Are you sure?' }

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
    = f.input :content, label: "الرد على الموضوع",  input_html:{ :minlength => "2" }
    %button.btn.btn-info{:type => "submit"} أضف تعليقك

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ar">
<head>
  <title>مشروعي | كل جديد في الريادة</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application',  'posts.coffee', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css">
  <link rel= "stylesheet" href= "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Cairo|El+Messiri" rel="stylesheet">
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" type="image/x-icon" href="https://lh3.googleusercontent.com/pQslXnsEXH4N6m5NFg5TIZUGYgAdtXtUJvtGr8DhSsv0MqAxnQ5LQ3yYvroh1ofIG8Qln8swCMc8kmZJeXp4Hw1f60v4nlE8zeo=w1920-h1080-rw-no" />
  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89887302-1', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript">var _kmq = _kmq || [];
var _kmk = _kmk || '936d2638b5fba54c3edb6f89313cd1cb9c0c4d91';
function _kms(u){
  setTimeout(function(){
    var d = document, f = d.getElementsByTagName('script')[0],
    s = d.createElement('script');
    s.type = 'text/javascript'; s.async = true; s.src = u;
    f.parentNode.insertBefore(s, f);
  }, 1);
}
_kms('//i.kissmetrics.com/i.js');
_kms('//scripts.kissmetrics.com/' + _kmk + '.2.js');
</script>
</head>
<body style="font-family: 'Cairo', sans-serif;">

    <%= render 'shared/navigation' %>

  
  <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
          <% end -%>
        </div>
      </div>
    </div>
  
  <div class="container">
    <%= yield %>
    </div>
    


  <%= render 'posts/footer' %>


</body>
</html>

app/views/posts/_footer.html.erb
<footer class="footer">
    <div class="container">
      <div class="row">
        <p class="footer-des"><span>مشروعي هي منصة تجمع كل جديد المشاريع الريادية و هي تحت الاطلاق التجريبي</span>.</p>
			<div class="copy-right">
				<p>جميع الحقوق محفوظة لـ مشروعي 2017 - طوّر بواسطة <a href="https://twitter.com/HekmatAr" rel="nofollow" target="_blank">حكمت</a></p>
			</div>
  		</div><!-- /.row -->
    </div>
  </footer>

app/views/posts/_form.html.haml
= simple_form_for @post, html: { multipart: true } do |f|
	- if @post.errors.any?
		#errors
			%h2
				= pluralize(@post.errors.count, "error")
				prevented this Post from saving
			%ul
				- @post.errors.full_messages.each do |msg|
					%li= msg


	.form-group
		= f.input :title,:label => "إسم المشروع", input_html: { class: 'form-control', :type => "text", :required => "required", :autofocus => true }
		%small#titleHelp.form-text.text-muted نرجو التأكد من كتابة إسم المشروع بالعربي

	.form-group
		= f.input :image,:label => "صورة", input_html: { class: 'form-group',"aria-describedby" => "fileHelp", :required => "required", :type => "file",:autofocus => true }

	.form-group
		= f.input :link,:label => "رابط المشروع ", input_html: { class: 'form-control', :type => "url", :value => "https://", :required => "required" , :autofocus => true, id:'url-input'}
		

	.form-group
		= f.input :description,:label => "نبذة مختصرة عن المشروع", input_html: { class: 'form-control', :rows => "3", :required => "required" , :autofocus => true, id: 'description'}
		%small#descriptionHelp.form-text.text-muted نرجو أن تكون النبذة دقيقة وواضحة
		
	
	%button.btn.btn-info{:type => "submit" } أضف مشروع
	

app/views/posts/edit.html.haml
.col-md-6.col-md-offset-3
    .row
        .panel.panel-default
            .panel-heading
                %h1 تعديل المشروع..
            .panel-body
                = simple_form_for @post, html: { multipart: true } do |f|
                    - if @post.errors.any?
                        #errors
                            %h2
                                = pluralize(@post.errors.count, "error")
                                prevented this Post from saving
                            %ul
                                - @post.errors.full_messages.each do |msg|
                                    %li= msg

                    .form-group
                        = f.input :title,:label => "إسم المشروع", input_html: { class: 'form-control', :type => "text", :required => ""}
                        %small#titleHelp.form-text.text-muted نرجو التأكد من كتابة إسم المشروع بالعربي
                    
                    .form-group
                        = f.input :image,:label => "صورة", input_html: { class: 'form-group',"aria-describedby" => "fileHelp", :required => "", :type => "file" }
                    
                    .form-group
                        = f.input :link,:label => "رابط المشروع ", input_html: { class: 'form-control', :type => "url", :placeholder => "https://", :required => "" }
                    
                    
                    .form-group
                        = f.input :description,:label => "نبذة مختصرة عن المشروع", input_html: { class: 'form-control', :rows => "3", :required => "" }
                        %small#descriptionHelp.form-text.text-muted نرجو أن تكون النبذة دقيقة وواضحة
                    
                    
                    %button.btn.btn-info{:type => "submit" } تعديل

app/views/posts/index.html.haml
- if user_signed_in?
    %p#intro
        أهلاً
        = current_user.name
        %br/
        %span
            شارك مشروعك وتابع مشاريع الأخرين 
- else
    %p#intro
        ماهو مشروعك؟
        %br/
        %span
            شارك مشروعك وتابع مشاريع الأخرين 
            
= render 'shared/recent'

.jumbotrom
    .container
        #posts
            - @posts.each do |post|
                .post
                    .post_image
                        = link_to (image_tag post.image.url(:small)), post
                    .post_content
                        .title
                            %h2= link_to post.title, post
                        .data.clearfix
                            %p.username
                                قبل
                                = time_ago_in_words(post.created_at)
                            %p.buttons
                                %span
                                    %i.fa.fa-check
                                    = post.get_likes.size
                                %span
                                    %i.fa.fa-comment
                                    = post.comments.count

app/views/posts/most_liked.html.haml
- if user_signed_in?
    %p#intro
        أهلاً
        = current_user.name
        %br/
        %span
            شارك مشروعك وتابع مشاريع الأخرين 
- else
    %p#intro
        ماهو مشروعك؟
        %br/
        %span
            شارك مشروعك وتابع مشاريع الأخرين 
            
= render 'shared/liked'

.jumbotrom
    .container
        #posts                     
            - @most_liked.each do |post|
                .post
                    .post_image
                        = link_to (image_tag post.image.url(:small)), post
                    .post_content
                        .title
                            %h2= link_to post.title, post
                        .data.clearfix
                            %p.username
                                بواسطة
                                = post.user.name
                            %p.buttons
                                %span
                                    %i.fa.fa-check
                                    = post.get_likes.size

app/views/posts/new.html.haml
.col-md-6.col-md-offset-3
    .row
        .panel.panel-default
            .panel-heading
                %h1 أضف مشروعك..
            .panel-body
                = render 'form'

app/views/posts/show.html.haml
#post_show
	%h1= @post.title
	%p.username
		قبل
		= time_ago_in_words(@post.created_at)
	.clearfix
		.post_image_description
			= image_tag @post.image.url(:medium)
			.description= simple_format(@post.description)
		.post_data
			= link_to "رابط المشروع", @post.link, class: "btn btn-warning btn-block"
			= link_to like_post_path(@post), method: :get, class: "data" do
				%i.fa.fa-check
				= @post.get_upvotes.size
				صح عليهم
			%p.data
				%i.fa.fa-comment
				= @post.comments.count
				عدد التعليقات
			- if @post.user == current_user
				= link_to "تعديل المشروع", edit_post_path(@post), class: "data"
				= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "متأكد؟" },class: "data"
		#random_post
			%h3 مشاريع أخرى
			.post
				.post_image
					= link_to (image_tag @random_post.image.url(:small)), post_path(@random_post)
				.post_content
					.title
						%h2= link_to @random_post.title, post_path(@random_post)
					.data.clearfix
						%p.username
							بواسطة
							= @random_post.user.name
						%p.buttons
							%span
								%i.fa.fa-check
									= @random_post.get_likes.size
							%span
								%i.fa.fa-check
									= @random_post.comments.count

#comments
	%h2.comment_count
		مناقشة المشروع
	- @comments.each do |comment|
		.comment
			%p.username= comment.user.name
			%p.content= comment.content
			- if @post.user == current_user
				= button_to 'مسح', [comment.post, comment], :method => :delete, data: { confirm: 'هل أنت متأكد؟..' }, class: "btn btn-link"
		
	= render "comments/form"

app/views/shared/_liked.html.erb
<ul class="nav nav-pills center-pills" role="tablist">
    <li><%= link_to 'الأحدث', posts_path %></i>
    <li class="active"><%= link_to 'الأبرز', posts_most_liked_path %></li>
</ul>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header navbar-right">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" style="float:left;">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a href="/"><p class="logo">مشروعي</p></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
      <% if user_signed_in? %>
      <li><%= link_to "أضف مشروعك +", new_post_path, class: "btn btn-info", :style => "color:white;" %></li>
      <li><%= link_to "حسابي", edit_user_registration_path, class: "btn btn-default" %></li>
      <li><%= link_to "تسجيل خروج", destroy_user_session_path, method: :delete,class: "btn btn-default" %></li>
      <% else %>
      <li><%= link_to "أضف مشروعك +", new_user_registration_url, class: "btn btn-info", :style => "color:white;" %></li>
      <li><%= link_to 'دخول',new_user_session_url, class: "btn btn-default" %></li>
      <li><%= link_to 'انضم إلينا الآن', new_user_registration_url, class: "btn btn-default" %></li>
      <% end %>
    </ul>
    </div>
  </nav>

app/views/shared/_recent.html.erb
<ul class="nav nav-pills center-pills" role="tablist">
    <li class="active"><%= link_to 'الأحدث', posts_path %></li>
    <li><%= link_to 'الأبرز', posts_most_liked_path %></li>
</ul>

app/views/shared/_slide.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="..." alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="..." alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="item">
  <img src="..." alt="...">
  <div class="carousel-caption">
    <h3>...</h3>
    <p>...</p>
  </div>
</div>

app/views/users/show.html.haml
= link_to current_user.name, edit_user_registration_path

#posts
    - @user_posts.each do |post|
        .post
            .post_image
                = link_to (image_tag post.image.url(:small)), post
            .post_content
                .title
                    %h2= link_to post.title, post
                .data.clearfix
                    %p.username
                        بواسطة
                        = post.user.name
                    %p.buttons
                        %span
                            %i.fa.fa-comments-o
                            = post.get_likes.size
                        %span
                            %i.fa.fa-check
                            = post.comments.count 